name: Backup Repository


on:
  
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches
          PAT: ${{ secrets.PAT }}

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'   
          
      - name: Create backup branch
        id: create_branch
        run: |
            echo "Creating backup branch"
            TIMESTAMP=$(TZ="US/Eastern" date +"%Y-%m-%d-%H-%M")
            TIMESTAMP=$(TZ="US/Eastern" date +"%Y-%m-%d-%H-%M")
            BRANCH_NAME="backup-$TIMESTAMP"
            echo "Branch name: $BRANCH_NAME"
            git checkout -b $BRANCH_NAME
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV    